name: Unit Tests

on:
  workflow_call:
  workflow_dispatch: # to trigger manually

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: pip install -r requirements-test.txt

      - name: Run unit tests
        run: python -m pytest -v
